version: "3.8"

services:
  grafana:
    image: grafana/grafana:5.1.0
    container_name: grafana
    volumes: 
      - ./config/grafana/provisioning:/etc/grafana/provisioning
    ports:
      - 3000:3000
    user: "104"

  broker:
    image: eclipse-mosquitto:1.6.10
    container_name: broker
    volumes:
      - "./config/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf"
    ports:
      - 1883:1883
      - 9001:9001

  influxdb:
    image: "influxdb:latest"
    container_name: influxdb
    ports:
      - '8086:8086'
      - '8083:8083'
    volumes:
      - influxdb-storage:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=technodrome
      - INFLUXDB_ADMIN_USER=master_splinter
      - INFLUXDB_ADMIN_PASSWORD=pizzapizza
  
  telegraf:
    image: telegraf:latest
    container_name: telegraf
    restart: always
    volumes:
      - ./config/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro

volumes:
    broker:
        driver: local
    influxdb-storage:
        driver: local