# Generated by Django 3.1.5 on 2021-02-08 01:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('read_interval', models.BigIntegerField(default=1800000)),
                ('sleep_interval', models.BigIntegerField(default=300000)),
                ('sleep', models.BooleanField(default=False)),
                ('publish_topic', models.CharField(max_length=500, null=True)),
                ('heartbeat_topic', models.CharField(max_length=500, null=True)),
                ('callback', models.CharField(max_length=256, null=True)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configs', to='core.device')),
            ],
            options={
                'db_table': 'device_config',
            },
        ),
    ]
